### ISSUE TITLE
[아두이노] 블루투스 통신 기능 만들기

### ISSUE THREAD

**Issue by simkyuwon** [inerplat/EyesON#7]
블루투스 시리얼 통신 아두이노에서 송신은 되는데 수신이 안됌

**Comment by inerplat** [comment]
시리얼 통신으로 '!'문자 보내는데 2byte char "33"을 수신함
아스키코드상으로 '!'가 33인데 수상함

**Comment by inerplat** [comment]
[What is the difference between Serial.write and Serial.print? And when are they used?](https://arduino.stackexchange.com/questions/10088/what-is-the-difference-between-serial-write-and-serial-print-and-when-are-they)

Serial에서 print함수쓰지말고 write함수로 쓰세요
